ClearChatCommandDescription: "A plugin that clears chats"
ClearChatCommand: "/clearchat"
ClearChatCommandAliases: ["chatclear", "clc"]
message.noPerm: "§cYou dont have permission to use this command."
message.chatSuccessfullyCleared: "§aThe chat got successfully cleared."